// js/lang.js

const translations = {
  fr: {
    hero: "Possédez le Son de l'Afrique",
    heroSub: "Découvrez, soutenez et possédez de la musique du Cameroun et au-delà.",

    browse: "Parcourir",
    new: "Nouveautés",
    trending: "Tendance au Cameroun",
    releases: "Nouvelles Sorties",
    charts: "Top Charts",
    genres: "Genres",

    singles: "Singles",
    albums: "Albums",

    view: "Voir",
    viewAll: "Voir tout",

    getStarted: "Commencer",
    fan: "Fan",
    artist: "Artiste",

    support: "Soutenir la musique africaine",
    supportSub: "Achetez des titres et soutenez directement les artistes",
    start: "Explorer",

    trendingSub: "À la une",
    newReleases: "Nouvelles sorties",
    exploreGenres: "Explorer les genres",

    home: "Accueil",
    library: "Bibliothèque",
    purchases: "Achats",
    settings: "Paramètres",
    settingsTitle: "Paramètres - JENGU",
    artistSettings: "Paramètres artiste",
    artistSettingsTitle: "Paramètres artiste - JENGU",
    profile: "Profil",
    fullName: "Nom complet",
    newPassword: "Nouveau mot de passe",
    mobilePayment: "Paiement Mobile",
    mobileNumber: "Numéro MTN / Orange",
    paymentUseNote: "Utilisé pour recevoir vos paiements ou achats",
    save: "Sauvegarder",
    settingsSaved: "Paramètres sauvegardés",
    accountSettings: "Compte",
    paymentSettings: "Paiements",
    downloadSettings: "Téléchargements",
    notificationSettings: "Notifications",
    securitySettings: "Sécurité",
    artistProfileSettings: "Profil artiste",
    storefrontSettings: "Vitrine",
    sellingSettings: "Vente",
    payoutSettings: "Détails de paiement",
    languageRegion: "Langue et région",
    regionPreference: "Marché préféré",
    downloadFormat: "Format de téléchargement",
    downloadQuality: "Qualité préférée",
    autoSavePurchases: "Ajouter automatiquement les achats à la bibliothèque",
    emailReceipts: "Recevoir les reçus d'achat par e-mail",
    releaseAlerts: "Recevoir les alertes de nouvelles sorties",
    exclusiveAlerts: "Recevoir les alertes de sorties exclusives",
    recentActivity: "Activité récente et appareils",
    recentActivityNote: "Gardez votre mot de passe sécurisé et surveillez les connexions à votre compte.",
    artistName: "Nom de l'artiste",
    artistBioLabel: "Biographie artiste",
    socialLinks: "Liens sociaux",
    storefrontHeadline: "Titre de vitrine",
    featuredGenre: "Genre mis en avant",
    defaultTrackPrice: "Prix par défaut du titre",
    defaultAlbumPrice: "Prix par défaut de l'album",
    previewLength: "Durée d'extrait",
    exclusiveByDefault: "Marquer les nouvelles sorties comme exclusives par défaut",
    payoutMethodLabel: "Méthode de paiement",
    legalName: "Nom légal",
    businessName: "Nom d'activité",
    salesAlerts: "Alertes de ventes en temps réel",
    payoutAlerts: "Alertes de paiements et retraits",
    releaseAlertsArtist: "Alertes pour publications et approbations",
    saveSettings: "Sauver",
    settingsRedirecting: "Redirection vers vos paramètres...",
    securityNoteArtist: "Utilisez une adresse e-mail professionnelle et mettez régulièrement à jour votre mot de passe.",
    fanSettingsIntro: "Gérez votre compte, vos paiements, vos téléchargements et vos notifications au même endroit.",
    autoSaveNote: "Conservez automatiquement chaque achat dans votre collection permanente.",
    receiptsNote: "Confirmations d'achat et historique des reçus.",
    releaseAlertsNote: "Restez proche des artistes et des nouvelles sorties marketplace.",
    exclusiveAlertsNote: "Soyez parmi les premiers lors des sorties digitales limitées.",
    artistSettingsIntro: "Gérez votre identité artiste, votre vitrine, vos paramètres de vente, vos paiements et vos alertes métier depuis un seul espace.",
    exclusiveByDefaultNote: "Utilisez l'exclusivité pour les sorties premium et les ventes directes aux fans.",
    salesAlertsNote: "Soyez averti quand des fans achètent vos sorties.",
    payoutAlertsNote: "Suivez l'état des paiements et l'avancement des retraits.",
    releaseAlertsArtistNote: "Recevez les notifications liées aux sorties en ligne et aux changements de catalogue.",

   /* AUTH */
    login: "Connexion",
    loginSub: "Accédez à vos achats et téléchargements",
    signup: "S'inscrire",
    signupSub: "Créez un compte pour acheter et télécharger",
    loginPageTitle: "Connexion - JENGU",
    signupPageTitle: "Inscription - JENGU",
    trackPageTitle: "Morceau - JENGU",
    chartsPageTitle: "Classements - JENGU",
    password: "Mot de passe",
    noAccount: "Pas encore de compte ?",
    haveAccount: "Vous avez déjà un compte ?",
    name: "Nom",
    email: "E-mail",
    forgot: "Mot de passe oublié ?",
    signupAsRole: "Je m'inscris en tant que :",
    loginAsRole: "Je me connecte en tant que :",
    roleFanDescSignup: "Acheter, decouvrir et telecharger",
    roleArtistDescSignup: "Publier et vendre votre musique",
    roleFanDescLogin: "Espace achat et bibliotheque",
    roleArtistDescLogin: "Espace dashboard et uploads",
    roleFanAccountCreated: "Compte fan cree ! Verifiez votre email pour confirmer.",
    roleArtistAccountCreated: "Compte artiste cree ! Verifiez votre email pour confirmer.",
    accountTypeFanMismatch: "Ce compte est fan. Choisissez Fan pour vous connecter.",
    accountTypeArtistMismatch: "Ce compte est artiste. Choisissez Artiste pour vous connecter.",
    artistLoginSuccess: "Connexion artiste reussie",
    userAlreadyExists: "Cet utilisateur existe deja",
    invalidCredentials: "Identifiants invalides",
    accessDenied: "Acces refuse",
    trackPriceRange: "Le prix du morceau doit etre entre 100 et 300 XAF",
    trackUploadedSuccess: "Morceau publie avec succes ✅",
    albumUploadedSuccess: "Album publie avec succes ✅",
    payoutLoadFailed: "Impossible de charger les paiements ❌",
    catalogEditLater: "Modification a connecter plus tard",
    catalogRemoved: "Supprime du catalogue",
    userNotAuthenticated: "Utilisateur non authentifie",
    purchasesApiUnavailable: "API des achats indisponible",
    purchasesFallbackNotice: "Serveur indisponible, affichage des achats locaux.",
    purchasesSearchPlaceholder: "Rechercher dans mes achats",
    purchasesSearchButton: "Rechercher",
    viewCartCta: "Panier",
    viewCartAria: "Voir le panier",
    creatorHubPageTitle: "Hub Createur - JENGU",
    creatorHubNav: "Hub Createur",
    creatorHubHeading: "Hub Createur",
    creatorHubSub: "Votre espace central pour publier des sorties, suivre les performances et piloter votre activite artiste.",
    creatorHubCardPublishTitle: "Publier une nouvelle sortie",
    creatorHubCardPublishBody: "Creez votre prochain morceau ou album avec un flux de publication pense pour les artistes.",
    creatorHubOpenPublisher: "Studio",
    creatorHubPerformanceTitle: "Performance et revenus",
    creatorHubPerformanceBody: "Consultez les streams, ventes et paiements depuis votre dashboard.",
    creatorHubOpenDashboard: "Dashboard",
    creatorHubOpenAnalytics: "Analytics",
    creatorHubCatalogTitle: "Gestion du catalogue",
    creatorHubCatalogBody: "Modifiez les metadonnees de vos sorties et gardez votre vitrine fraiche.",
    creatorHubManageCatalog: "Catalogue",
    creatorHubSettingsTitle: "Parametres artiste",
    creatorHubSettingsBody: "Controlez votre branding, vos paiements et vos reglages de vente.",
    creatorHubOpenSettings: "Reglages",
    publishNewReleasePageTitle: "Publier une nouvelle sortie - JENGU",
    publishNewReleaseNav: "Publier une nouvelle sortie",
    publishNewReleaseHeading: "Publier une nouvelle sortie",
    publishNewReleaseSub: "Choisissez le type de sortie que vous voulez publier. Vous pouvez mettre en ligne un morceau ou un album complet.",
    publishSingleTrackTitle: "Morceau solo",
    publishSingleTrackBody: "Flux rapide pour singles, freestyles ou sorties piste par piste.",
    publishAlbumEpTitle: "Album / EP",
    publishAlbumEpBody: "Lancez un projet complet et fixez un prix album pour vos fans.",
    payoutsPageTitle: "Paiements artiste - JENGU",
    artistPayoutsHeading: "Paiements artiste",
    searchPayoutPlaceholder: "Rechercher un paiement...",
    noPayoutsFound: "Aucun paiement trouve",
    amountLabel: "Montant",
    dateLabel: "Date",

    trackTitlePlaceholder: "Titre du morceau",
    trackNameLabel: "Titre",
    artist: "Artiste",
    topTracks: "Top Tracks",
    buyAlbum: "Acheter",
    buy: "Acheter",
    preview: "▶ Lecture",
    pausePreview: "Pause",
    previewUnavailable: "Apercu indisponible",
    trackNotFound: "Morceau introuvable",
    trackExclusive: "Exclusif",
    trackCoverAlt: "Pochette du morceau",
    trackMetaHQ: "MP3 Haute Qualite",
    trackMetaDelivery: "Livraison instantanee",
    trackMetaSecure: "Paiement securise",
    trackPaymentHint: "Choisissez une methode pour continuer vers le checkout.",
    payment: "Paiement",
    paymentMethod: "Méthode de paiement",
    mobilePrompt: "Entrez votre numero Mobile Money",
    payNow: "Payer",
    gatewayStatusChecking: "Verification de la passerelle de paiement...",
    gatewayStatusOnline: "JenguPay est en ligne. Paiement actif.",
    gatewayStatusOffline: "JenguPay est indisponible. Verifiez le serveur puis reessayez.",
    paymentFailed: "Paiement echoue. Veuillez reessayer.",
    cartEmpty: "Panier vide",
    chooseMethod: "Choisissez un moyen de paiement",
    mobileRequired: "Numero requis pour Mobile Money",
    paymentStarted: "Paiement en ligne initialise",
    paymentConfirmed: "Paiement confirme",
    gatewayUnavailable: "Paiement impossible: JenguPay est hors ligne.",
    cancel: "Annuler",
    paymentUnavailable: "Paiement bientôt disponible",
    loadingError: "Erreur de chargement",
    blog: "Blog",
    read: "Lire",
    artistBio: "Biographie de l'artiste...",
    tracks: "Morceaux",
    articleTitlePlaceholder: "Titre de l'article",
    loading: "Chargement...",
    confirmEmail: "Veuillez confirmer votre email avant de vous connecter.",
    loginSuccess: "Connexion réussie",
    mobileMoney: "Mobile Money",
    card: "Carte",
    confirm: "Confirmer",
    readyDownload: "Album prêt",
    downloadAvailable: "Téléchargement disponible.",
    downloadZip: "Télécharger ZIP",
    choosePayment: "Choisissez un moyen de paiement",
    purchaseConfirmed: "Votre achat a été confirmé.",
    close: "Fermer",
    tracklist: "Liste des titres",
    libraryEmpty: "🎧 Votre bibliothèque est vide",
    noPurchases: "Aucun achat pour le moment",
    pleaseLogin: "Veuillez vous connecter",
    payouts: "Paiements",
    dashboard: "Dashboard",
    catalog: "Catalogue",
    uploadTrack: "Upload",
    uploadAlbum: "Upload",
    earnings: "Gains",
    payoutHistory: "Historique des paiements",
    quickActions: "Actions rapides",
    viewCatalog: "Catalogue",
    publishTrack: "Publier",
    publishAlbum: "Publier",
    selectGenre: "Choisir un genre",
    artistAccountRequired: "Compte artiste requis",
    noEarnings: "Aucun gain",
    withdrawalRequested: "Retrait demandé",
    withdraw: "Retirer",
    albumPriceRange: "Le prix doit être entre 1000–2000 XAF",
    analytics: "Analytics",
    genreHeader: "Explorer les Genres",
    libraryHeader: "Ma Bibliothèque",
    purchasesHeader: "Mes Achats",
    chartsTitle: "Top Charts",
    chartsSubtitle: "Le classement premium des morceaux les plus ecoutes et les plus achetes cette semaine.",
    chartsMetricDaily: "Mis a jour chaque jour",
    chartsMetricEditorial: "Selection editoriale",
    chartsMetricCheckout: "Checkout instantane",
    chartsTagGlobal: "Global",
    chartsTagRising: "Rising",
    chartsNoTracks: "Aucun morceau disponible pour le moment.",

    /* COMMON UI + ADMIN */
    search: "Rechercher",
    users: "Utilisateurs",
    artists: "Artistes",
    transactions: "Transactions",
    promotions: "Promotions",
    fraud: "Fraude",
    manageUsers: "Gerer les utilisateurs",
    searchUsers: "Rechercher un utilisateur",
    username: "Nom d'utilisateur",
    joined: "Inscrit le",
    status: "Statut",
    actions: "Actions",
    albumNamePlaceholder: "Nom de l'album",

    /* ARTIST PRICING PAGE */
    pricingPageTitle: "Plans & Tarifs Artiste – JENGU",
    pricingKicker: "Plans & Tarifs Artiste",
    pricingHeroTitle: "Tarification Simple et Équitable pour les Artistes Africains",
    pricingHeroSub: "Commencez gratuitement. Passez au Pro quand vous êtes prêt.",
    pricingNavBrowse: "Parcourir la Musique",
    pricingNavPlans: "Plans Artiste",
    pricingNavSignupFree: "Commencer",
    planFreeName: "Artiste Gratuit",
    planFreeForever: "à vie",
    planFreeCommission: "commission de la plateforme",
    planFreeF1: "Publiez et vendez votre musique immédiatement",
    planFreeF2: "Vitrine artiste et profil public",
    planFreeF3: "Statistiques de ventes de base",
    planFreeF4: "Paiements directs et sécurisés (XAF)",
    planFreeF5: "Support plateforme standard",
    planFreeCta: "Commencer",
    planProBadge: "⭐ Recommandé",
    planProName: "Artiste Pro",
    planProPeriod: "XAF / an",
    planProCommission: "taux de commission réduit",
    planProF1: "Tout le plan Gratuit, plus :",
    planProF2: "Commission réduite (8–10%)",
    planProF3: "Analytics avancés et tableau de bord des ventes",
    planProF4: "Mise en avant artiste",
    planProF5: "Support prioritaire",
    planProF6: "Personnalisation avancée de la vitrine",
    planProF7: "Outils de campagnes promotionnelles",
    planProF8: "Accès anticipé aux nouvelles fonctionnalités",
    planProCta: "Upgrade",
    comparisonLabel: "Détail des Fonctionnalités",
    comparisonHeading: "Comparer les Plans",
    compColFeature: "Fonctionnalité",
    compColFree: "Artiste Gratuit",
    compColPro: "Artiste Pro ⭐",
    compR1: "Commission par vente",
    compR2: "Uploader et vendre des morceaux",
    compR3: "Uploader et vendre des albums",
    compR4: "Vitrine et profil artiste",
    compR5: "Paiements directs des fans (XAF)",
    compR6: "Statistiques de ventes de base",
    compR7: "Tableau de bord analytics avancés",
    compR8: "Mise en avant artiste",
    compR9: "Outils de campagne promotionnelle",
    compR10: "Personnalisation de vitrine avancée",
    compR11: "Niveau de support",
    compR12: "Accès anticipé aux nouvelles fonctionnalités",
    compValStandard: "Standard",
    compValPriority: "Prioritaire",
    faqLabel: "Questions Fréquentes",
    faqHeading: "FAQ",
    faqQ1: "Puis-je commencer à vendre sans rien payer ?",
    faqA1: "Oui. Le plan Artiste Gratuit ne coûte rien et vous permet de publier et vendre votre musique immédiatement. JENGU prend 15% uniquement quand un fan achète votre titre ou album — vous gardez le reste sans aucun coût initial.",
    faqQ2: "Que signifie exactement 8–10% pour le plan Pro ?",
    faqA2: "La commission du plan Pro varie entre 8% et 10% selon le type de sortie et la tranche de prix. Par rapport aux 15% standard, un artiste Pro gagnant 100 000 XAF par an conserve 5 000 à 7 000 XAF de plus — bien au-dessus du coût annuel de 10 000 XAF.",
    faqQ3: "Quand serai-je considéré pour la mise en avant ?",
    faqA3: "Les artistes Pro sont inclus dans le pool éditorial et considérés pour les emplacements mis en avant sur la page d'accueil, selon la qualité du catalogue, l'activité de publication et l'engagement des fans. Ce n'est pas garanti, mais le statut Pro augmente significativement votre visibilité.",
    faqQ4: "Comment fonctionnent les paiements ?",
    faqA4: "Les gains des achats des fans s'accumulent dans votre tableau de bord artiste. Vous pouvez demander un paiement à tout moment. Les paiements sont effectués en XAF via mobile money. Les artistes Gratuits et Pro partagent le même processus.",
    faqQ5: "Puis-je passer du Gratuit au Pro à tout moment ?",
    faqA5: "Oui. Vous pouvez passer au Pro à tout moment depuis votre tableau de bord artiste. Votre catalogue, historique des ventes et abonnés sont conservés automatiquement. Le tarif Pro est de 10 000 XAF par an, facturé annuellement.",
    faqQ6: "La plateforme est-elle disponible dans toute l'Afrique francophone ?",
    faqA6: "JENGU est conçu pour les artistes et fans du Cameroun et de l'Afrique francophone. Les artistes de tout pays peuvent créer un compte, publier de la musique et commencer à vendre. La couverture des paiements peut varier selon la région — consultez vos paramètres de compte.",
    pricingFinalHeading: "Commencez à Vendre Gratuitement",
    pricingFinalSub: "Créez votre compte artiste en quelques minutes. Aucun coût initial. Passez au Pro quand vous êtes prêt.",
    pricingFinalBtn1: "Join",
    pricingFinalBtn2: "Discover",

    /* UPGRADE BANNERS */
    upgradeBannerFreePlanTitle: "Vous êtes sur le plan Gratuit — 15% de commission par vente",
    upgradeBannerFreePlanSub: "Passez au Pro pour 8–10% de commission + mise en avant + analytics avancés.",
    upgradeBannerAnalyticsTitle: "Débloquez les analytics avancés avec le plan Pro",
    upgradeBannerAnalyticsSub: "Les artistes Pro bénéficient d'un tableau de bord complet, d'insights d'audience et d'une commission réduite à 8–10%.",
    upgradeBannerUploadTitle: "Plan Gratuit ? Vous gardez 85% de chaque vente",
    upgradeBannerUploadSub: "Passez au Pro et gardez jusqu'à 92% — plus mise en avant et outils promotionnels.",
    upgradeBannerCta: "Upgrade",

    /* PLANS STRIP (index.html) */
    plansKicker: "Plans Artiste",
    plansStripTitle: "Conçu pour les Artistes à Chaque Étape",
    plansStripSub: "Commencez gratuitement sans coût initial — nous ne gagnons que quand vous vendez. Passez au Pro pour des frais réduits, des analytics avancés et une mise en avant.",
    plansFreeArtist: "Artiste Gratuit",
    plansProArtist: "Artiste Pro ⭐",
    plansFreeCommission: "15% de commission par vente",
    plansProCommission: "8–10% de commission / an",
    plansViewPlans: "Plans",
    sellYourMusic: "Vendre Votre Musique",
    discoverNav: "Decouvrir",
    musicNav: "Musique",
    moviesNav: "Films",
    eventsNav: "Evenements",
    merchNav: "Merch",
    creatorsNav: "Createurs",
    discoverPageTitle: "Decouvrir - JENGU",
    moviesPageTitle: "Films - JENGU",
    eventsPageTitle: "Evenements - JENGU",
    merchPageTitle: "Merch - JENGU",
    merchProductPageTitle: "Produit merch - JENGU",
    creatorsPageTitle: "Createurs - JENGU",
    creatorPageTitle: "Createur - JENGU",
    discoverKicker: "Discovery Unifiee",
    discoverHeading: "Decouvrez La Musique, Les Films, Les Evenements Et Le Merch",
    discoverSub: "Parcourez chaque categorie dans un flux premium, puis filtrez et triez selon ce que vous voulez collectionner.",
    discoverTabAll: "Tout",
    discoverTabMusic: "Musique",
    discoverTabMovies: "Films",
    discoverTabEvents: "Evenements",
    discoverTabMerch: "Merch",
    exploreMoreHeading: "Explorer",
    exploreMoreMusicBody: "Restez sur la musique ici, puis ouvrez le flux complet pour explorer toutes les categories.",
    exploreMoreMoviesBody: "Gardez cette page centree sur les films, puis passez au flux global pour decouvrir plus.",
    exploreMoreEventsBody: "Parcourez les evenements ici, puis ouvrez le flux global pour decouvrir plus.",
    exploreMoreMerchBody: "Restez sur le merch ici, puis ouvrez le flux global pour explorer toutes les categories.",
    discoverSortLabel: "Trier",
    discoverSortPopular: "Les Plus Populaires",
    discoverSortNewest: "Les Plus Recents",
    discoverSortPriceAsc: "Prix: Croissant",
    discoverSortPriceDesc: "Prix: Decroissant",
    discoverListingSingle: "resultat",
    discoverListingPlural: "resultats",
    discoverNoItems: "Aucun element trouve pour ce filtre.",
    discoverLoadMore: "Charger",
    moviesHeading: "Marketplace Films",
    moviesSub: "Films independants premium, documentaires et cinema culturel court format.",
    moviesCard1Title: "Film En Vedette",
    moviesCard1Body: "Minuit a Douala",
    moviesCard2Title: "Selection Documentaire",
    moviesCard2Body: "Les Voix du Marche",
    moviesCard3Title: "Liste Curatee",
    moviesCard3Body: "Recits d'Afrique Francophone",
    eventsHeading: "Marketplace Evenements",
    eventsSub: "Decouvrez les prochaines soirees creatives, projections et experiences culturelles live.",
    eventsCard1Title: "A Venir",
    eventsCard1Body: "Nuit des Createurs de Yaounde • 14 Mai",
    eventsCard2Title: "Evenement Cinema",
    eventsCard2Body: "Week-end Afro-Cinema • 22 Mai",
    eventsCard3Title: "Session Musique",
    eventsCard3Body: "Salon d'Ecoute JENGU • 31 Mai",
    eventsTicketsHeading: "Billets disponibles",
    buyTicket: "Acheter",
    merchHeading: "Marketplace Merch",
    merchSub: "Vetements, collector packs et objets physiques vendus directement par les createurs.",
    merchFeaturedTitle: "Merch en vedette",
    merchFeaturedBody: "Drops limites et editions signatures.",
    merchCreatorDropsTitle: "Drops createurs",
    merchCreatorDropsBody: "Pieces exclusives liees a vos artistes favoris.",
    merchDeliveryTitle: "Livraison premium",
    merchDeliveryBody: "Expedition suivie et disponibilites en temps reel.",
    viewMerchDetails: "Voir",
    relatedMerch: "Merch associe",
    chooseVariant: "Choisir une variante",
    stockLabel: "Stock",
    creatorLabel: "Createur",
    shippingLabel: "Livraison",
    merchAddToCart: "Ajouter",
    merchOutOfStock: "Rupture de stock",
    merchAdded: "Merch ajoute au panier",
    merchManageTitle: "Gerer votre merch",
    merchManageBody: "Publiez des vetements, objets collector et bundles physiques dans votre boutique.",
    openMerchStudio: "Studio",
    uploadMerch: "Upload Merch",
    uploadMerchPageTitle: "Upload Merch - JENGU",
    merchFormTitle: "Titre du produit",
    merchFormDescription: "Description",
    merchFormImages: "Images produit",
    merchFormVariants: "Variantes (taille/couleur)",
    merchFormStock: "Stock total",
    merchFormPrice: "Prix (XAF)",
    merchFormShipping: "Zones de livraison",
    merchFormSubmit: "Publier",
    merchPublishedSuccess: "Produit merch publie",
    creatorsHeading: "Profils Createurs",
    creatorsSub: "Liste multi-categorie de createurs actifs en musique, films, evenements et merch.",
    creatorOfferings: "Offres Marketplace",
    creatorFollow: "Suivre",
    creatorShare: "Partager",
    creatorProducts: "Produits",
    creatorFollowers: "Abonnes",
    moviePageTitle: "Film - JENGU",
    eventPageTitle: "Evenement - JENGU",
      albumPageTitle: "Album - JENGU",
    pdpDetails: "Details",
    pdpCreator: "Createur",
    pdpRelated: "Similaires",
    pdpMoreFrom: "Du même createur",
    pdpYouMayLike: "Vous aimerez aussi",
    pdpSynopsis: "Synopsis",
    pdpEventInfo: "Infos",
    pdpSpecs: "Caracteristiques",
    pdpDuration: "Duree",
    pdpGenre: "Genre",
    pdpDate: "Date",
    pdpLocation: "Lieu",
    pdpTickets: "Billets",
    artistPricingNav: "Tarifs Artiste",
    sellOnJenguNav: "Vendre sur JENGU",
    homeEyebrow: "Marketplace Premium De Culture Numerique",
    homeGatewayKicker: "Portes d'Entree",
    homeGatewayHeading: "Commencez par une Categorie",
    homeGatewaySub: "Des points d'entree choisis pour acheter, regarder et sortir.",
    homeGatewayMusicTitle: "Musique en Vedette",
    homeGatewayMusicSub: "Albums et morceaux a posseder maintenant.",
    homeGatewayMoviesTitle: "Films en Vedette",
    homeGatewayMoviesSub: "Nouveaux films, docs et courts formats.",
    homeGatewayEventsTitle: "Evenements a Venir",
    homeGatewayEventsSub: "Projections, sets et nuits creatrices.",
    homeGatewayMerchTitle: "Merch en Vedette",
    homeGatewayMerchSub: "Apparel, objets collector et drops physiques.",
    homeFeaturedMoviesTitle: "Films en Vedette",
    homeFeaturedEventsTitle: "Evenements en Vedette",
    homeFeaturedMerchTitle: "Merch en Vedette",
    homeViewAll: "Voir tout",
    homeMovieSpot1Title: "Minuit a Douala",
    homeMovieSpot1Meta: "Drame",
    homeMovieSpot2Title: "Les Voix du Marche",
    homeMovieSpot2Meta: "Documentaire",
    homeMovieSpot3Title: "Lever du Sahel",
    homeMovieSpot3Meta: "Court metrage",
    homeEventSpot1Title: "Nuit des Createurs de Yaounde",
    homeEventSpot1Meta: "14 Mai",
    homeEventSpot2Title: "Week-end Afro-Cinema",
    homeEventSpot2Meta: "22 Mai",
    homeEventSpot3Title: "Salon d'Ecoute JENGU",
    homeEventSpot3Meta: "31 Mai",
    homeMerchSpot1Title: "T-shirt Signature JENGU Live",
    homeMerchSpot1Meta: "Edition limitee",
    homeMerchSpot2Title: "Pack Collector Afro-Cinema",
    homeMerchSpot2Meta: "Bundle physique",
    homeMerchSpot3Title: "Capsule Creator Night",
    homeMerchSpot3Meta: "Stock reduit",
    homeCuratedKicker: "Selection Editoriale",
    homeCuratedHeading: "Collections Curatees",
    homeCuratedSub: "Une selection breve signee par notre desk editorial.",
    homeCollectionLabel: "Collection",
    homeStaffPicksLabel: "Choix du Desk",
    homeCityEditLabel: "Edit Ville",
    homeCurated1Title: "Nouvelles Voix Francophones",
    homeCurated1Sub: "Nouveaux artistes et cineastes a collectionner.",
    homeCurated2Title: "Week-end Voir + Ecouter",
    homeCurated2Sub: "Une selection rapide pour ce week-end.",
    homeCurated3Title: "Douala Underground",
    homeCurated3Sub: "Une coupe locale de sorties et de moments live.",
    homeCuratedMerchTitle: "Collector Shelf",
    homeCuratedMerchSub: "Les drops merch a prendre avant rupture.",
    homePulseFeaturedMusic: "Musique en Vedette",
    homePulseTrendingReleases: "Sorties Tendance",
    homePulseFeaturedMovies: "Films en Vedette",
    homePulseUpcomingEvents: "Evenements a Venir",
    homePulseFeaturedMerch: "Merch en Vedette",
    homeLoadingFeaturedMusic: "Chargement de la musique...",
    homeLoadingTrending: "Chargement des tendances...",
    homeLoadingMovies: "Chargement des films...",
    homeLoadingEvents: "Chargement des evenements...",
    homeFeaturedMusicSoon: "Musique en vedette bientot disponible",
    homeTrendingSoon: "Sorties tendance bientot disponibles",
    homeMoviesSoon: "Films en vedette bientot disponibles",
    homeEventsSoon: "Evenements bientot disponibles",
    homeArtistStripKicker: "Pour les artistes prets a vendre",
    homeFinalHeading: "Construisez Votre Storefront sur JENGU",
    homeFinalSub: "Creez votre compte. Publiez. Commencez a vendre.",
    homeArtistSignup: "Join",
    homeTypeTrack: "Morceau",
    homeTypeAlbum: "Album",
    homeTrackDownload: "Telechargement du morceau",
    homeAlbumDownload: "Telechargement de l'album",
    homeIndependentCreator: "Createur independant",
    homeReleaseCta: "Ecouter • Acheter • Telecharger",
    homeUntitled: "Sans titre",
    kindTrack: "morceau",
    kindAlbum: "album",
    kindFilm: "film",
    kindDocumentary: "documentaire",
    kindLive: "live",
    kindScreening: "projection",
    kindApparel: "apparel",
    kindCollectible: "collector"
  },

  en: {
    hero: "Own the Sound of Africa",
    heroSub: "Discover, support, and own music from Cameroon and beyond.",

    browse: "Browse",
    new: "New Releases",
    trending: "Trending in Cameroon",
    releases: "New Releases",
    charts: "Top Charts",
    genres: "Genres",

    singles: "Singles",
    albums: "Albums",

    view: "View",
    viewAll: "View All",

    getStarted: "Get Started",
    fan: "Fan",
    artist: "Artist",

    support: "Support African Music",
    supportSub: "Buy tracks and empower artists directly",
    start: "Start Exploring",

    trendingSub: "Hot right now",
    newReleases: "New Releases",
    exploreGenres: "Explore Genres",

    home: "Home",
    library: "Library",
    purchases: "Purchases",
    settings: "Settings",
    settingsTitle: "Settings - JENGU",
    artistSettings: "Artist Settings",
    artistSettingsTitle: "Artist Settings - JENGU",
    profile: "Profile",
    fullName: "Full name",
    newPassword: "New password",
    mobilePayment: "Mobile Payment",
    mobileNumber: "MTN / Orange number",
    paymentUseNote: "Used to receive your payouts or purchases",
    save: "Save",
    settingsSaved: "Settings saved",
    accountSettings: "Account",
    paymentSettings: "Payments",
    downloadSettings: "Downloads",
    notificationSettings: "Notifications",
    securitySettings: "Security",
    artistProfileSettings: "Artist Profile",
    storefrontSettings: "Storefront",
    sellingSettings: "Selling",
    payoutSettings: "Payout Details",
    languageRegion: "Language and Region",
    regionPreference: "Preferred market",
    downloadFormat: "Download format",
    downloadQuality: "Preferred quality",
    autoSavePurchases: "Automatically save purchases to library",
    emailReceipts: "Email me purchase receipts",
    releaseAlerts: "Send me new release alerts",
    exclusiveAlerts: "Send me exclusive drop alerts",
    recentActivity: "Recent activity and devices",
    recentActivityNote: "Keep your password secure and monitor sign-ins to your account.",
    artistName: "Artist name",
    artistBioLabel: "Artist bio",
    socialLinks: "Social links",
    storefrontHeadline: "Storefront headline",
    featuredGenre: "Featured genre",
    defaultTrackPrice: "Default track price",
    defaultAlbumPrice: "Default album price",
    previewLength: "Preview length",
    exclusiveByDefault: "Mark new releases as exclusive by default",
    payoutMethodLabel: "Payout method",
    legalName: "Legal name",
    businessName: "Business name",
    salesAlerts: "Real-time sales alerts",
    payoutAlerts: "Payout and withdrawal alerts",
    releaseAlertsArtist: "Publishing and approval alerts",
    saveSettings: "Save",
    settingsRedirecting: "Redirecting to your settings...",
    securityNoteArtist: "Use a professional email address and update your password regularly.",
    fanSettingsIntro: "Manage your account, payments, downloads, and notifications from one place.",
    autoSaveNote: "Keep every purchase in your permanent collection automatically.",
    receiptsNote: "Purchase confirmations and receipt records.",
    releaseAlertsNote: "Stay close to artists and new marketplace drops.",
    exclusiveAlertsNote: "Be first when limited digital releases arrive.",
    artistSettingsIntro: "Manage your artist identity, storefront, selling defaults, payouts, and business alerts from one control center.",
    exclusiveByDefaultNote: "Use exclusivity for direct-to-fan drops and premium releases.",
    salesAlertsNote: "Know when fans purchase your releases.",
    payoutAlertsNote: "Stay updated on payout status and settlement progress.",
    releaseAlertsArtistNote: "Get notified about live releases and catalog changes.",

    /* AUTH */
    login: "Login",
    loginSub: "Access your purchases and downloads",
    signup: "Sign Up",
    signupSub: "Create an account to buy and download",
    loginPageTitle: "Login - JENGU",
    signupPageTitle: "Sign Up - JENGU",
    trackPageTitle: "Track - JENGU",
    chartsPageTitle: "Top Charts - JENGU",
    password: "Password",
    noAccount: "Don’t have an account?",
    haveAccount: "Already have an account?",
    name: "Name",
    email: "Email",
    forgot: "Forgot Password?",
    signupAsRole: "I am signing up as:",
    loginAsRole: "I am logging in as:",
    roleFanDescSignup: "Buy, discover, and download music",
    roleArtistDescSignup: "Publish and sell your music",
    roleFanDescLogin: "Buyer and library space",
    roleArtistDescLogin: "Dashboard and upload space",
    roleFanAccountCreated: "Fan account created! Check your email to confirm.",
    roleArtistAccountCreated: "Artist account created! Check your email to confirm.",
    accountTypeFanMismatch: "This is a fan account. Choose Fan to sign in.",
    accountTypeArtistMismatch: "This is an artist account. Choose Artist to sign in.",
    artistLoginSuccess: "Artist login successful",
    userAlreadyExists: "User already exists",
    invalidCredentials: "Invalid credentials",
    accessDenied: "Access denied",
    trackPriceRange: "Track price must be between 100 and 300 XAF",
    trackUploadedSuccess: "Track uploaded successfully ✅",
    albumUploadedSuccess: "Album uploaded successfully ✅",
    payoutLoadFailed: "Failed to load payouts ❌",
    catalogEditLater: "Edit later hookup pending",
    catalogRemoved: "Removed from catalog",
    userNotAuthenticated: "User not authenticated",
    purchasesApiUnavailable: "Purchases API unavailable",
    purchasesFallbackNotice: "Server unavailable, showing local purchases.",
    purchasesSearchPlaceholder: "Search my purchases",
    purchasesSearchButton: "Search",
    viewCartCta: "Cart",
    viewCartAria: "View cart",
    creatorHubPageTitle: "Creator Hub - JENGU",
    creatorHubNav: "Creator Hub",
    creatorHubHeading: "Creator Hub",
    creatorHubSub: "Your central space for publishing releases, tracking performance, and managing your artist business.",
    creatorHubCardPublishTitle: "Publish New Release",
    creatorHubCardPublishBody: "Create your next track or album with an artist-first publishing flow.",
    creatorHubOpenPublisher: "Studio",
    creatorHubPerformanceTitle: "Performance & Revenue",
    creatorHubPerformanceBody: "Check streams, sales, and payout status from your dashboard.",
    creatorHubOpenDashboard: "Dashboard",
    creatorHubOpenAnalytics: "Analytics",
    creatorHubCatalogTitle: "Catalog Management",
    creatorHubCatalogBody: "Edit release metadata and keep your storefront fresh.",
    creatorHubManageCatalog: "Catalog",
    creatorHubSettingsTitle: "Artist Settings",
    creatorHubSettingsBody: "Control branding, payouts, and sales defaults.",
    creatorHubOpenSettings: "Settings",
    publishNewReleasePageTitle: "Publish New Release - JENGU",
    publishNewReleaseNav: "Publish New Release",
    publishNewReleaseHeading: "Publish New Release",
    publishNewReleaseSub: "Choose the release type you want to publish. You can upload a single track or a full album.",
    publishSingleTrackTitle: "Single Track",
    publishSingleTrackBody: "Fast release flow for singles, freestyles, or focused track drops.",
    publishAlbumEpTitle: "Album / EP",
    publishAlbumEpBody: "Launch a complete project and set album-level pricing for your fans.",
    payoutsPageTitle: "Artist Payouts - JENGU",
    artistPayoutsHeading: "Artist Payouts",
    searchPayoutPlaceholder: "Search payout...",
    noPayoutsFound: "No payouts found",
    amountLabel: "Amount",
    dateLabel: "Date",

    trackTitlePlaceholder: "Track Title",
    trackNameLabel: "Title",
    artist: "Artist",
    topTracks: "Top Tracks",
    buyAlbum: "Buy",
    buy: "Buy",
    preview: "▶ Preview",
    pausePreview: "Pause",
    previewUnavailable: "Preview unavailable",
    trackNotFound: "Track not found",
    trackExclusive: "Exclusive",
    trackCoverAlt: "Track cover",
    trackMetaHQ: "High Quality MP3",
    trackMetaDelivery: "Instant Delivery",
    trackMetaSecure: "Secure Checkout",
    trackPaymentHint: "Choose a method to continue to checkout.",
    payment: "Payment",
    paymentMethod: "Payment method",
    mobilePrompt: "Enter your Mobile Money number",
    payNow: "Pay",
    gatewayStatusChecking: "Checking payment gateway...",
    gatewayStatusOnline: "JenguPay is online. Payments are active.",
    gatewayStatusOffline: "JenguPay is unavailable. Start the server and try again.",
    paymentFailed: "Payment failed. Please try again.",
    cartEmpty: "Cart is empty",
    chooseMethod: "Choose a payment method",
    mobileRequired: "Mobile number is required for Mobile Money",
    paymentStarted: "Online payment initialized",
    paymentConfirmed: "Payment confirmed",
    gatewayUnavailable: "Payment unavailable: JenguPay is offline.",
    cancel: "Cancel",
    paymentUnavailable: "Payment coming soon",
    loadingError: "Loading error",
    blog: "Blog",
    read: "Read",
    artistBio: "Artist biography...",
    tracks: "Tracks",
    articleTitlePlaceholder: "Article title",
    loading: "Loading...",
    confirmEmail: "Please confirm your email before logging in.",
    loginSuccess: "Login successful",
    mobileMoney: "Mobile Money",
    card: "Card",
    confirm: "Confirm",
    readyDownload: "Album Ready",
    downloadAvailable: "Download available.",
    downloadZip: "Download ZIP",
    choosePayment: "Choose a payment method",
    purchaseConfirmed: "Your purchase has been confirmed.",
    close: "Close",
    tracklist: "Tracklist",
    libraryEmpty: "🎧 Your library is empty",
    noPurchases: "No purchases yet",
    pleaseLogin: "Please log in",
    payouts: "Payouts",
    dashboard: "Dashboard",
    catalog: "Catalog",
    uploadTrack: "Upload",
    uploadAlbum: "Upload",
    earnings: "Earnings",
    payoutHistory: "Payout History",
    quickActions: "Quick Actions",
    viewCatalog: "Catalog",
    publishTrack: "Publish",
    publishAlbum: "Publish",
    selectGenre: "Choose a genre",
    artistAccountRequired: "Artist account required",
    noEarnings: "No earnings",
    withdrawalRequested: "Withdrawal requested",
    withdraw: "Withdraw",
    albumPriceRange: "Album price must be between 1000–2000 XAF",
    analytics: "Analytics",
    genreHeader: "Explore Genres",
    libraryHeader: "My Library",
    purchasesHeader: "My Purchases",
    chartsTitle: "Top Charts",
    chartsSubtitle: "The premium ranking of the most streamed and purchased tracks this week.",
    chartsMetricDaily: "Updated Daily",
    chartsMetricEditorial: "Editorial Picks",
    chartsMetricCheckout: "Instant Checkout",
    chartsTagGlobal: "Global",
    chartsTagRising: "Rising",
    chartsNoTracks: "No tracks available right now.",

    /* COMMON UI + ADMIN */
    search: "Search",
    users: "Users",
    artists: "Artists",
    transactions: "Transactions",
    promotions: "Promotions",
    fraud: "Fraud",
    manageUsers: "Manage Users",
    searchUsers: "Search users",
    username: "Username",
    joined: "Joined",
    status: "Status",
    actions: "Actions",
    albumNamePlaceholder: "Album Name",

    /* ARTIST PRICING PAGE */
    pricingPageTitle: "Artist Plans & Pricing – JENGU",
    pricingKicker: "Artist Plans & Pricing",
    pricingHeroTitle: "Simple, Fair Pricing for African Artists",
    pricingHeroSub: "Start free. Upgrade when you're ready to grow.",
    pricingNavBrowse: "Browse Music",
    pricingNavPlans: "Artist Plans",
    pricingNavSignupFree: "Start",
    planFreeName: "Free Artist",
    planFreeForever: "forever",
    planFreeCommission: "platform commission",
    planFreeF1: "Upload and sell music immediately",
    planFreeF2: "Artist storefront & public profile",
    planFreeF3: "Basic sales analytics",
    planFreeF4: "Secure direct fan payments (XAF)",
    planFreeF5: "Standard platform support",
    planFreeCta: "Start",
    planProBadge: "⭐ Recommended",
    planProName: "Pro Artist",
    planProPeriod: "XAF / year",
    planProCommission: "lower commission rate",
    planProF1: "Everything in Free, plus:",
    planProF2: "Lower platform commission (8–10%)",
    planProF3: "Advanced analytics & sales dashboard",
    planProF4: "Featured artist consideration",
    planProF5: "Priority support",
    planProF6: "Enhanced storefront customization",
    planProF7: "Promotional campaign tools",
    planProF8: "Early access to new features",
    planProCta: "Upgrade",
    comparisonLabel: "Feature Breakdown",
    comparisonHeading: "Compare Plans",
    compColFeature: "Feature",
    compColFree: "Free Artist",
    compColPro: "Pro Artist ⭐",
    compR1: "Platform commission per sale",
    compR2: "Upload & sell tracks",
    compR3: "Upload & sell albums",
    compR4: "Artist storefront & profile",
    compR5: "Direct fan payments (XAF)",
    compR6: "Basic sales analytics",
    compR7: "Advanced analytics dashboard",
    compR8: "Featured artist placement consideration",
    compR9: "Promotional campaign tools",
    compR10: "Enhanced storefront customization",
    compR11: "Support tier",
    compR12: "Early access to new features",
    compValStandard: "Standard",
    compValPriority: "Priority",
    faqLabel: "Common Questions",
    faqHeading: "FAQ",
    faqQ1: "Can I start selling without paying anything?",
    faqA1: "Yes. The Free Artist plan costs nothing and lets you upload and sell music immediately. JENGU only takes 15% when a fan purchases your track or album — you keep the rest with no upfront cost ever.",
    faqQ2: "What exactly does 8–10% mean for the Pro plan?",
    faqA2: "Pro plan commission varies between 8% and 10% depending on release type and price tier. Compared to the standard 15%, a Pro artist earning 100 000 XAF in a year keeps 5 000–7 000 XAF more — well above the 10 000 XAF annual plan cost.",
    faqQ3: "When will I be considered for Featured Artist placement?",
    faqA3: "Pro artists are added to the editorial review pool and considered for homepage and browse featured slots based on catalog quality, release activity, and fan engagement. There is no guarantee, but Pro status significantly increases your visibility on the platform.",
    faqQ4: "How do payouts work?",
    faqA4: "Earnings from fan purchases accumulate in your artist dashboard. You can request a payout at any time. Payouts are processed in XAF via mobile money. Both Free and Pro artists share the same payout process.",
    faqQ5: "Can I upgrade from Free to Pro anytime?",
    faqA5: "Yes. You can upgrade to Pro at any time from your artist dashboard. Your existing catalog, sales history, and fan followers all carry over automatically. The Pro fee is 10 000 XAF per year, billed annually.",
    faqQ6: "Is the platform available across all of Francophone Africa?",
    faqA6: "JENGU is built for artists and fans across Cameroon and Francophone Africa. Artists from any country can create an account, upload music, and start selling. Payment and payout coverage may vary by region — check your account settings for country-specific details.",
    pricingFinalHeading: "Start Selling for Free",
    pricingFinalSub: "Create your artist account in minutes. No upfront cost. Upgrade when you're ready to grow beyond the basics.",
    pricingFinalBtn1: "Join",
    pricingFinalBtn2: "Discover",

    /* UPGRADE BANNERS */
    upgradeBannerFreePlanTitle: "You're on the Free plan — 15% commission per sale",
    upgradeBannerFreePlanSub: "Upgrade to Pro for 8–10% commission + featured placement + advanced analytics.",
    upgradeBannerAnalyticsTitle: "Unlock advanced analytics with Pro",
    upgradeBannerAnalyticsSub: "Pro artists get a full sales dashboard, audience insights, and lower 8–10% commission.",
    upgradeBannerUploadTitle: "On Free plan? You keep 85% of each sale",
    upgradeBannerUploadSub: "Upgrade to Pro and keep up to 92% — plus featured placement and promo tools.",
    upgradeBannerCta: "Upgrade",

    /* PLANS STRIP (index.html) */
    plansKicker: "Artist Plans",
    plansStripTitle: "Built for Artists at Every Stage",
    plansStripSub: "Start free with no upfront cost — we only earn when you do. Scale up to Pro when you're ready for lower fees, advanced analytics, and featured placement.",
    plansFreeArtist: "Free Artist",
    plansProArtist: "Pro Artist ⭐",
    plansFreeCommission: "15% commission per sale",
    plansProCommission: "8–10% commission / year",
    plansViewPlans: "Plans",
    sellYourMusic: "Sell Your Music",
    discoverNav: "Discover",
    musicNav: "Music",
    moviesNav: "Movies",
    eventsNav: "Events",
    merchNav: "Merch",
    creatorsNav: "Creators",
    discoverPageTitle: "Discover - JENGU",
    moviesPageTitle: "Movies - JENGU",
    eventsPageTitle: "Events - JENGU",
    merchPageTitle: "Merch - JENGU",
    merchProductPageTitle: "Merch Product - JENGU",
    creatorsPageTitle: "Creators - JENGU",
    creatorPageTitle: "Creator - JENGU",
    discoverKicker: "Unified Discovery",
    discoverHeading: "Discover Across Music, Movies, Events, And Merch",
    discoverSub: "Browse every category in one premium feed, then filter and sort based on what you want to collect next.",
    discoverTabAll: "All",
    discoverTabMusic: "Music",
    discoverTabMovies: "Movies",
    discoverTabEvents: "Events",
    discoverTabMerch: "Merch",
    exploreMoreHeading: "Explore",
    exploreMoreMusicBody: "Stay in music here, then open the full feed to discover across all categories.",
    exploreMoreMoviesBody: "Keep this page focused on movies, then jump to the full feed for wider discovery.",
    exploreMoreEventsBody: "Browse events here, then open the full feed when you want broader discovery.",
    exploreMoreMerchBody: "Keep merch focused here, then open the full feed to discover across categories.",
    discoverSortLabel: "Sort",
    discoverSortPopular: "Most Popular",
    discoverSortNewest: "Newest",
    discoverSortPriceAsc: "Price: Low to High",
    discoverSortPriceDesc: "Price: High to Low",
    discoverListingSingle: "listing",
    discoverListingPlural: "listings",
    discoverNoItems: "No items found for this filter.",
    discoverLoadMore: "Load",
    moviesHeading: "Movies Marketplace",
    moviesSub: "Premium independent films, documentaries, and short-format culture cinema.",
    moviesCard1Title: "Featured Film",
    moviesCard1Body: "Midnight In Douala",
    moviesCard2Title: "Documentary Pick",
    moviesCard2Body: "Voices Of The Market",
    moviesCard3Title: "Curated List",
    moviesCard3Body: "Stories From Francophone Africa",
    eventsHeading: "Events Marketplace",
    eventsSub: "Discover upcoming creator-led nights, screenings, and live cultural experiences.",
    eventsCard1Title: "Upcoming",
    eventsCard1Body: "Yaounde Creator Night • 14 May",
    eventsCard2Title: "Film Event",
    eventsCard2Body: "Afro-Film Weekend • 22 May",
    eventsCard3Title: "Music Session",
    eventsCard3Body: "JENGU Listening Room • 31 May",
    eventsTicketsHeading: "Available Tickets",
    buyTicket: "Buy",
    merchHeading: "Merch Marketplace",
    merchSub: "Apparel, collector bundles, and physical products sold directly by creators.",
    merchFeaturedTitle: "Featured merch",
    merchFeaturedBody: "Limited drops and signature editions.",
    merchCreatorDropsTitle: "Creator drops",
    merchCreatorDropsBody: "Exclusive pieces tied to your favorite artists.",
    merchDeliveryTitle: "Premium delivery",
    merchDeliveryBody: "Tracked shipping and live availability.",
    viewMerchDetails: "View",
    relatedMerch: "Related merch",
    chooseVariant: "Choose a variant",
    stockLabel: "Stock",
    creatorLabel: "Creator",
    shippingLabel: "Shipping",
    merchAddToCart: "Add",
    merchOutOfStock: "Out of stock",
    merchAdded: "Merch added to cart",
    merchManageTitle: "Manage your merch",
    merchManageBody: "Publish apparel, collectibles, and physical bundles in your storefront.",
    openMerchStudio: "Studio",
    uploadMerch: "Upload Merch",
    uploadMerchPageTitle: "Upload Merch - JENGU",
    merchFormTitle: "Product title",
    merchFormDescription: "Description",
    merchFormImages: "Product images",
    merchFormVariants: "Variants (size/color)",
    merchFormStock: "Total stock",
    merchFormPrice: "Price (XAF)",
    merchFormShipping: "Shipping zones",
    merchFormSubmit: "Publish",
    merchPublishedSuccess: "Merch product published",
    creatorsHeading: "Creator Profiles",
    creatorsSub: "Multi-category creator listings across music, movies, events, and merch.",
    creatorOfferings: "Marketplace Offerings",
    creatorFollow: "Follow",
    creatorShare: "Share",
    creatorProducts: "Products",
    creatorFollowers: "Followers",
    moviePageTitle: "Film - JENGU",
    eventPageTitle: "Event - JENGU",
      albumPageTitle: "Album - JENGU",
    pdpDetails: "Details",
    pdpCreator: "Creator",
    pdpRelated: "Related",
    pdpMoreFrom: "More from creator",
    pdpYouMayLike: "You may also like",
    pdpSynopsis: "Synopsis",
    pdpEventInfo: "Info",
    pdpSpecs: "Specs",
    pdpDuration: "Duration",
    pdpGenre: "Genre",
    pdpDate: "Date",
    pdpLocation: "Location",
    pdpTickets: "Tickets",
    artistPricingNav: "Artist Pricing",
    sellOnJenguNav: "Sell on Jengu",
    homeEyebrow: "Premium Digital Culture Marketplace",
    homeGatewayKicker: "Category Gateways",
    homeGatewayHeading: "Start With A Category",
    homeGatewaySub: "Curated entry points to buy, watch, and show up.",
    homeGatewayMusicTitle: "Featured Music",
    homeGatewayMusicSub: "Albums and tracks worth owning now.",
    homeGatewayMoviesTitle: "Featured Movies",
    homeGatewayMoviesSub: "New films, docs, and standout shorts.",
    homeGatewayEventsTitle: "Upcoming Events",
    homeGatewayEventsSub: "Live screenings, sets, and creator nights.",
    homeGatewayMerchTitle: "Featured Merch",
    homeGatewayMerchSub: "Apparel, collectibles, and physical drops.",
    homeFeaturedMoviesTitle: "Featured Movies",
    homeFeaturedEventsTitle: "Featured Events",
    homeFeaturedMerchTitle: "Featured Merch",
    homeViewAll: "View All",
    homeMovieSpot1Title: "Midnight In Douala",
    homeMovieSpot1Meta: "Drama",
    homeMovieSpot2Title: "Voices Of The Market",
    homeMovieSpot2Meta: "Documentary",
    homeMovieSpot3Title: "Sahel Sunrise",
    homeMovieSpot3Meta: "Short Film",
    homeEventSpot1Title: "Yaounde Creator Night",
    homeEventSpot1Meta: "14 May",
    homeEventSpot2Title: "Afro-Film Weekend",
    homeEventSpot2Meta: "22 May",
    homeEventSpot3Title: "JENGU Listening Room",
    homeEventSpot3Meta: "31 May",
    homeMerchSpot1Title: "JENGU Live Signature Tee",
    homeMerchSpot1Meta: "Limited edition",
    homeMerchSpot2Title: "Afro-Film Collector Pack",
    homeMerchSpot2Meta: "Physical bundle",
    homeMerchSpot3Title: "Creator Night Capsule",
    homeMerchSpot3Meta: "Low stock",
    homeCuratedKicker: "Curated Editorial",
    homeCuratedHeading: "Curated Collections",
    homeCuratedSub: "A brief selection from our editorial desk.",
    homeCollectionLabel: "Collection",
    homeStaffPicksLabel: "Staff Picks",
    homeCityEditLabel: "City Edit",
    homeCurated1Title: "New Francophone Voices",
    homeCurated1Sub: "New artists and filmmakers worth collecting.",
    homeCurated2Title: "Weekend Watch + Listen",
    homeCurated2Sub: "Quick cross-category picks for this weekend.",
    homeCurated3Title: "Douala Underground",
    homeCurated3Sub: "A local cut of releases and live moments.",
    homeCuratedMerchTitle: "Collector Shelf",
    homeCuratedMerchSub: "Merch drops to secure before they sell out.",
    homePulseFeaturedMusic: "Featured Music",
    homePulseTrendingReleases: "Trending Releases",
    homePulseFeaturedMovies: "Featured Movies",
    homePulseUpcomingEvents: "Upcoming Events",
    homePulseFeaturedMerch: "Featured Merch",
    homeLoadingFeaturedMusic: "Loading music...",
    homeLoadingTrending: "Loading trends...",
    homeLoadingMovies: "Loading movies...",
    homeLoadingEvents: "Loading events...",
    homeFeaturedMusicSoon: "Featured music coming soon",
    homeTrendingSoon: "Trending releases coming soon",
    homeMoviesSoon: "Featured movies coming soon",
    homeEventsSoon: "Events coming soon",
    homeArtistStripKicker: "For Artists Ready To Sell",
    homeFinalHeading: "Build Your Creator Storefront On JENGU",
    homeFinalSub: "Create your account. Publish. Start selling.",
    homeArtistSignup: "Join",
    homeTypeTrack: "Track",
    homeTypeAlbum: "Album",
    homeTrackDownload: "Track Download",
    homeAlbumDownload: "Album Download",
    homeIndependentCreator: "Independent Creator",
    homeReleaseCta: "Listen • Buy • Download",
    homeUntitled: "Untitled",
    kindTrack: "track",
    kindAlbum: "album",
    kindFilm: "film",
    kindDocumentary: "documentary",
    kindLive: "live",
    kindScreening: "screening",
    kindApparel: "apparel",
    kindCollectible: "collectible"
  }
};

/* =========================
   LANGUAGE STATE
========================= */
export function getLang(){
  return localStorage.getItem("lang") || "fr";
}

export function setLang(lang){
  localStorage.setItem("lang", lang);
}

export function translate(key){
  return translations[getLang()]?.[key] || key;
}

/* =========================
   APPLY LANGUAGE
========================= */
export function applyLang(){

  const lang = getLang();
  document.documentElement.lang = lang;

  const pageTitleKey = document.body?.dataset?.i18nTitle;
  if(pageTitleKey){
    const title = translations[lang]?.[pageTitleKey];
    if(title) document.title = title;
  }

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.dataset.i18n;

    const text = translations[lang]?.[key];

    if(!text) return;

      if(el.tagName === "INPUT"){
      el.placeholder = text;
      } else if(el.tagName === "IMG"){
        el.alt = text;
    } else {
      el.textContent = text;
    }
  });

  document.querySelectorAll("[data-i18n-aria]").forEach(el => {
    const key = el.dataset.i18nAria;
    const text = translations[lang]?.[key];

    if(text){
      el.setAttribute("aria-label", text);
    }
  });

  const navMap = {
    "/": "home",
    "/index.html": "home",
    "/discover.html": "discoverNav",
    "/browse.html": "musicNav",
    "/movies.html": "moviesNav",
    "/events.html": "eventsNav",
    "/merch.html": "merchNav",
    "/merch-product.html": "merchNav",
    "/creators.html": "creatorsNav",
    "/creator.html": "creatorsNav",
    "/genres.html": "genres",
    "/charts.html": "charts",
    "/new-releases.html": "new",
    "/settings.html": "settings",
    "/user/library.html": "library",
    "/user/purchases.html": "purchases",
    "/user/settings.html": "settings",
    "/artist/dashboard.html": "dashboard",
    "/artist/catalog.html": "catalog",
    "/artist/upload-track.html": "uploadTrack",
    "/artist/upload-album.html": "uploadAlbum",
    "/artist/upload-merch.html": "uploadMerch",
    "/artist/payouts.html": "payouts",
    "/artist/analytics.html": "analytics",
    "/artist/settings.html": "settings",
    "/artist-pricing.html": "artistPricingNav",
    "/artist/signup.html": "sellOnJenguNav"
  };

  document.querySelectorAll(".side-menu a[href]").forEach(el => {
    const href = el.getAttribute("href");
    const key = navMap[href];

    if(!key) return;

    const text = translations[lang]?.[key];
    if(text) el.textContent = text;
  });

  /* update switch label */
  const btn = document.getElementById("langBtn");
  if(btn){
    btn.textContent = lang.toUpperCase() + " ▾";
  }
}

/* =========================
   TOGGLE LANGUAGE
========================= */
export function toggleLang(){
  const current = getLang();
  const next = current === "fr" ? "en" : "fr";

  setLang(next);
  applyLang();
  attachLangButton();
}

function ensureLangButton(){
  let btn = document.getElementById("langBtn");
  if(btn) return btn;

  if(!document.body) return null;

  btn = document.createElement("button");
  btn.id = "langBtn";
  btn.type = "button";
  btn.className = "lang";
  btn.setAttribute("aria-label", "Toggle language");

  btn.style.position = "fixed";
  btn.style.top = "14px";
  btn.style.right = "14px";
  btn.style.zIndex = "999";
  btn.style.padding = "7px 10px";
  btn.style.borderRadius = "999px";
  btn.style.border = "1px solid rgba(255,255,255,0.2)";
  btn.style.background = "rgba(15,17,21,0.92)";
  btn.style.color = "#ffffff";
  btn.style.backdropFilter = "blur(10px)";
  btn.style.cursor = "pointer";

  document.body.appendChild(btn);
  return btn;
}

/* =========================
   ATTACH BUTTON HANDLER
========================= */
export function attachLangButton(){
  const btn = ensureLangButton();
  if(btn){
    btn.onclick = toggleLang;
    btn.textContent = getLang().toUpperCase() + " ▾";
  }
}

/* =========================
   INIT (CLEAN)
========================= */
export function initLang(){

  // apply immediately
  applyLang();

  // attach click handler
  if(document.readyState === "loading"){
    document.addEventListener("DOMContentLoaded", attachLangButton);
  } else {
    attachLangButton();
  }
}